[WIP] Added few tests for generated subsystems
hal/testsuite pull request #205
Opened 2016-10-13 14:24 UTC by honza-kasik

Depends on #204 , still needs work, this part of code is ready for review, though...

2016-10-17 06:44 UTC, honza-kasik commented
Ready to be merged.

2016-10-17 18:15 UTC, rhatlapa commented
This contains also changes from !204. Lets wait with having merged !204, then rebase and review.

2016-10-31 14:27 UTC, honza-kasik commented
Ready to be merged!

2016-11-03 15:58 UTC, rhatlapa requested changes
You are forgetting javadocs, please add them at least for all public non test methods and classes. Ideally you can add also javadoc for testcase classes.

2016-11-03 15:58 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/requestcontroller/RequestControllerSubsystemTestCase.java
> +    public void verifyActiveRequests() throws Exception {
This name looks more as some internal method name than test name, I suggest renaming it to something like `activeRequestsTest` or something similar.

2016-11-03 15:58 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/requestcontroller/RequestControllerSubsystemTestCase.java
> +        value.assertSuccess();
You probably wanted rather to use `assertDefinedValue()`

2016-11-03 15:58 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/requestcontroller/RequestControllerSubsystemTestCase.java
> +                ReadAttributeOption.INCLUDE_DEFAULTS);
Here should be NOT_INCLUDE_DEFAULTS

2016-11-03 15:58 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/requestcontroller/RequestControllerSubsystemTestCase.java
> +                TRACK_INDIVIDUAL_ENDPOINTS, ReadAttributeOption.INCLUDE_DEFAULTS);
You should use NOT_INCLUDE_DEFAULTS

2016-11-03 15:58 UTC, rhatlapa commented on common/src/main/java/org/jboss/hal/testsuite/page/config/RequestControllerPage.java
> +public class RequestControllerPage extends ConfigPage implements Navigatable {
Missing javadoc.

2016-11-03 15:58 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/naming/NamingTestCase.java
> +    public void verifyRemoteNamingServiceExists() {
Don't use `verify` word in naming of test methods.

2016-11-03 15:58 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/noconfig/NoConfigSubsystemTestCaseAbstract.java
> +public abstract class NoConfigSubsystemTestCaseAbstract {
Javadoc please

2016-11-03 15:58 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/noconfig/NoConfigSubsystemTestCaseAbstract.java
> +    public void verifySubsystemIsPresentByNavigatingToIt(String subsystemLabel) {
javadoc please

2016-11-03 15:58 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/securitymanager/SecurityManagerTestCase.java
> +    }
Make the tests independent to each other => remove need for sequence.

2016-11-03 15:58 UTC, rhatlapa commented on common/src/main/java/org/jboss/hal/testsuite/fragment/shared/modal/WizardWindowWithAdvancedSelectBoxOptions.java
> +public class WizardWindowWithAdvancedSelectBoxOptions extends WizardWindow {
javadoc please

2016-11-03 15:58 UTC, rhatlapa commented on common/src/main/java/org/jboss/hal/testsuite/fragment/shared/modal/WizardWindowWithAdvancedSelectBoxOptions.java
> +    }
Javadoc for each public method please

2016-11-03 15:58 UTC, rhatlapa commented on common/src/main/java/org/jboss/hal/testsuite/fragment/shared/modal/WizardWindowWithOptionalFields.java
> +public class WizardWindowWithOptionalFields extends WizardWindow {
javadoc please

2016-11-03 15:58 UTC, rhatlapa commented on common/src/main/java/org/jboss/hal/testsuite/fragment/shared/modal/WizardWindowWithOptionalFields.java
> +    }
Javadoc for each public method please

2016-11-03 15:58 UTC, rhatlapa commented on common/src/main/java/org/jboss/hal/testsuite/page/config/JsfPage.java
> +public class JsfPage extends ConfigPage implements Navigatable {
Javadoc

2016-11-03 15:58 UTC, rhatlapa commented on common/src/main/java/org/jboss/hal/testsuite/fragment/shared/modal/WizardWindowWithOptionalFields.java
> +        maximizeWindow();
there is needed such hack as maximizing window, interesting.

2016-11-03 15:58 UTC, rhatlapa commented on common/src/main/java/org/jboss/hal/testsuite/page/config/NamingPage.java
> +public class NamingPage extends TreeNavigationPage {
javadoc

2016-11-03 15:58 UTC, rhatlapa commented on common/src/main/java/org/jboss/hal/testsuite/page/config/SecurityManagerPage.java
> +public class SecurityManagerPage extends TreeNavigationPage {
javadoc

2016-11-04 08:05 UTC, honza-kasik commented
Fixed Javadoc and few other things, still needs work on `SecurityManagerTestCase`

2016-11-04 11:13 UTC, honza-kasik commented
`SecurityManagerTestCase` was fixed, but it needs to be expanded, after https://issues.jboss.org/browse/HAL-1225 is resolved. If CI check goes well this PR can be merged.

2016-11-08 07:19 UTC, rhatlapa commented
Please rebase (in order to run checks again, now as part of the checks is also findbugs)

2016-11-08 07:19 UTC, rhatlapa approved these changes

2016-11-08 07:27 UTC, honza-kasik commented
Rebased, all checks passed.

2016-11-08 07:35 UTC, rhatlapa commented
Thanks, merging.

2016-11-08 07:35 UTC, merged