Added tests for singleton subsystem
hal/testsuite pull request #212
Opened 2016-11-08 13:10 UTC by honza-kasik

2016-11-08 13:14 UTC, honza-kasik commented
Ready to be merged

2016-11-11 14:48 UTC, rhatlapa requested changes
There is no need for subsystem addresses to be special counted for domain, this is automatically handled by creaper based on client config.

Also don't change pattern for usage of different Creaper Operations classes, we should stay consistent. It will be nicer from dev UX.

2016-11-11 14:48 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/singleton/ElectionPolicyTestCase.java
> +            INFINISPAN_SUBSYSTEM_ADDRESS = ConfigUtils.isDomain() ? Address.of("profile", "full-ha").and("subsystem", "infinispan") : Address.subsystem("infinispan"),
The check for doamin isn't needed, the prefix for subsystem in domain is done based on management client configuration.

2016-11-11 14:48 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/singleton/ElectionPolicyTestCase.java
> +        operations.add(SINGLETON_POLICY_EDIT_ADDRESS.and(ELECTION_POLICY, "simple")).assertSuccess();
I suggest using batch operation, which takes care of cleaning after itself if not all of the substeps succeed.

2016-11-11 14:48 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/singleton/ElectionPolicyTestCase.java
> +    private static final class SocketBindingResources implements AutoCloseable {
Why AutoCloseable when you are not using it this way, I suggest just providing clean method, which is in this case more representative. AutoCloseable is mainly meant for resources which have allocated some resources needing to be unallocated, such as streams, connections. Not as cleanup method of what was done. You can create interface for the purpose of cleaning if you like.

2016-11-11 14:48 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/singleton/ElectionPolicyTestCase.java
> +            socketBindingResources.close();
should be probably in some finally block, the removeCacheContainer may throw exception

2016-11-11 14:48 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/singleton/ElectionPolicyTestCase.java
> +            SingletonSubsystemOperations.withOperations(operations).removeCacheContainer(CACHE_CONTAINER_RESOURCE_ADDRESS);
Use commonly used pattern for creating custom operations class => instantiate via OnlineManagementClient client and not operations. Also don't use Factory pattern for this purpose, it should stay consistent with the other Operations classes.

2016-11-11 14:48 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/singleton/ElectionPolicyTestCase.java
> +        public ModelNode getSocketBindingsAsModelNodeList() {
Javadoc

2016-11-11 14:48 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/singleton/ElectionPolicyTestCase.java
> +        public String getSocketBindingNamesSeparatedByNewline() {
Javadoc please

2016-11-11 14:48 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/singleton/ElectionPolicyTestCase.java
> +        private List<String> createSocketBindings() throws CommandFailedException, IOException {
Why throws `CommandFailedException`?

2016-11-11 14:48 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/singleton/ElectionPolicyTestCase.java
> +    private static final class SocketBindingResources implements AutoCloseable {
Javadoc please

2016-11-11 14:48 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/singleton/ElectionPolicyTestCase.java
> +        public void close() throws Exception {
Javadoc please

2016-11-11 14:48 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/singleton/SingletonPolicyTestCase.java
> +            INFINISPAN_SUBSYSTEM_ADDRESS = ConfigUtils.isDomain() ? Address.of("profile", "full-ha").and("subsystem", "infinispan") : Address.subsystem("infinispan"),
As above, no need the special handling for domain.

2016-11-11 14:48 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/singleton/SingletonSubsystemOperations.java
> +    }
Please don't use this pattern for Operations classes, it makes inconsistent usage for them and makes it rather confusing than helping.

2016-11-11 14:48 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/singleton/SingletonSubsystemOperations.java
> +    }
Make constructor public and the attribute it gets should be `OnlineManagementClient`

2016-11-14 08:11 UTC, honza-kasik commented
Thanks! Worked in suggestions, ready to be merged.

2016-11-14 14:48 UTC, rhatlapa requested changes

2016-11-14 14:48 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/singleton/ElectionPolicyTestCase.java
> +    private static final OnlineManagementClient client = ManagementClientProvider.withProfile("full-ha");
Where did disapear client for standalone?

2016-11-14 15:09 UTC, honza-kasik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/singleton/ElectionPolicyTestCase.java
> +    private static final OnlineManagementClient client = ManagementClientProvider.withProfile("full-ha");
Thanks! Fixed!

2016-11-16 11:03 UTC, rhatlapa approved these changes

2016-11-16 11:03 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/singleton/ElectionPolicyTestCase.java
> +                operations.remove(this.socketBindingGroupAddress.and(SOCKET_BINDING_TYPE, socketBinding)).assertSuccess();
removeIfExists might be more reasonable in this case, but ok.

2016-11-16 11:03 UTC, rhatlapa commented
LGTM, please squash and I shall merge.

2016-11-18 12:43 UTC, honza-kasik commented
Squashed and ready t be merged!

2016-11-18 15:38 UTC, rhatlapa commented
Thanks, merging.

2016-11-18 15:38 UTC, merged