Fixed RequestControllerSubsystemTestCase
hal/testsuite pull request #215
Opened 2016-11-22 16:13 UTC by honza-kasik

* Fixed buggs in `toggleTrackIndividualEndpoints`
* Fixed attributes presence based on server mode, see https://github.com/wildfly/wildfly-core/blob/5ff6433a5f06051ce8c29c654e9957d463e9ce77/request-controller/src/main/java/org/wildfly/extension/requestcontroller/RequestControllerExtension.java

2016-11-28 10:14 UTC, honza-kasik commented
I reviewed the possibility to have `@Category` for class, but it doesn't work with `@Category(Shared.class)` for class and `@Category(Standalone.class)` for one test - it runs all of them in domain mode and if I would revert it it would be IMHO less clear which test runs when...

2016-11-28 16:27 UTC, rhatlapa requested changes

2016-11-28 16:27 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/requestcontroller/RequestControllerSubsystemTestCase.java
>      public void verifyActiveRequests() throws Exception {
This test can be updated also for domain, the runtime attributes are specific for single server => you need to check it on the server level and not on profile level => all tests can remain shared for standalone and domain, just domain requires handling for single server in domain rather then whole profile.

2016-12-01 15:04 UTC, honza-kasik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/requestcontroller/RequestControllerSubsystemTestCase.java
>      public void verifyActiveRequests() throws Exception {
Maybe I am not looking everywhere but I do not see a way how to see active request on server in web console gui. That looks like a possible bug.

2016-12-07 07:58 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/requestcontroller/RequestControllerSubsystemTestCase.java
>      public void verifyActiveRequests() throws Exception {
Yes, I also believe it is a bug, I don't see it there either.

2016-12-07 07:59 UTC, rhatlapa approved these changes

2016-12-07 08:00 UTC, rhatlapa commented
LGTM, merging. Note, there should be added test for the `active-requests` in domain even though the functionality is currently missing in HAL

2016-12-07 08:00 UTC, merged