[WIP] Undertow filters
hal/testsuite pull request #231
Opened 2017-01-05 09:25 UTC by honza-kasik

2017-01-10 15:36 UTC, honza-kasik commented
This needs further elaboration on how to obtain `ResourceTable` since the structure of page is little bit tricky.

2017-01-12 13:44 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/HostTestCase.java
> +    private static final Address REQUEST_LIMIT_FILTER_ADDRESS = UndertowConstants.UNDERTOW_FILTERS_ADDRESS.and("request-limit", REQUEST_LIMIT_FILTER_NAME);
Using name + Address seems as common pattern which could be avoided, as such I have created PR to creaper https://github.com/wildfly-extras/creaper/pull/148 allowing to retrieve the resource name from the address.

2017-01-12 13:44 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/HostTestCase.java
> +        operations.add(HOST_ADDRESS.and("filter-ref", REQUEST_LIMIT_FILTER_NAME)).assertSuccess();
I would suggest making use of batch operation here.

2017-01-12 13:44 UTC, rhatlapa commented on common/src/main/java/org/jboss/hal/testsuite/fragment/shared/table/ResourceTableRowFragment.java
> +        return getRoot().getAttribute("class").contains("cellTableSelectedRow");
You should use the defined constant here.

2017-01-27 14:14 UTC, honza-kasik commented
Now waiting for job to complete to find out if there are any regressions!

2017-02-20 07:45 UTC, honza-kasik commented
Looks like it is not breaking any more test, so it is ready to be merged.

2017-02-23 13:37 UTC, rhatlapa requested changes
Generally LGTM, just few suggestions for improvements, please provide your feedback or fixes.

Also update commit messages to not contain WIP before merging.

2017-02-23 13:37 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/HostTestCase.java
> +    private static final Address REQUEST_LIMIT_FILTER_ADDRESS = UndertowConstants.UNDERTOW_FILTERS_ADDRESS.and("request-limit", REQUEST_LIMIT_FILTER_NAME);
There is released Creaper snapshot version 1.5.1-SNAPSHOT in https://repository.jboss.org/nexus/content/repositories/snapshots/org/wildfly/extras/creaper/ containing this functionality.

2017-02-23 13:37 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/HostTestCase.java
> +        operations.add(GZIP_PAGE_FILTER_ADDRESS).assertSuccess();
Doesn't seem to be removed in after class

2017-02-23 13:37 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/HostTestCase.java
> +                page.getConfigFragment().getResourceManager().isResourcePresent(GZIP_PAGE_FILTER_NAME));
You should also verify that it was added to model and not that it is just updated in UI

2017-02-23 13:37 UTC, rhatlapa commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/HostTestCase.java
> +                manager.isResourcePresent(REWRITE_FILTER_NAME));
You should check it also in model.

2017-02-23 13:37 UTC, rhatlapa commented on common/src/main/java/org/jboss/hal/testsuite/fragment/shared/table/ResourceTableRowFragment.java
> +    public boolean isSelected() {
Javadoc, to make clear what is selected, whole table, row in table or cell in table,...

2017-02-23 13:37 UTC, rhatlapa commented on common/src/main/java/org/jboss/hal/testsuite/fragment/shared/util/ResourceManager.java
>   */
I suggest to remove this, as git blame tells you more and this is becoming outdated.

2017-02-23 13:37 UTC, rhatlapa commented on common/src/main/java/org/jboss/hal/testsuite/fragment/shared/util/ResourceManager.java
> +    public boolean isResourcePresent(String name) {
Not sure regarding the timeouts, there might be worth testing that the item is there immediately, but OK.

2017-02-23 13:37 UTC, rhatlapa commented on common/src/main/java/org/jboss/hal/testsuite/page/config/UndertowHostPage.java
> +public class UndertowHostPage extends UndertowHTTPPage {
Javadoc

2017-02-23 13:37 UTC, rhatlapa commented on common/src/main/java/org/jboss/hal/testsuite/page/config/UndertowHostPage.java
> +    public ConfigFragment switchToReferenceToFilterSubTab() {
The name doesn't need to correspond exactly to the subtitle as that subtitle can be changed. Suggesting to rename it to `switchToFilterReferencesSubTab` or add javadoc.

2017-02-23 13:37 UTC, rhatlapa commented on common/src/main/java/org/jboss/hal/testsuite/page/config/UndertowHostPage.java
> +    public void addReferenceToFilter(String filterName) {
javadoc

2017-02-23 14:09 UTC, honza-kasik commented
Thanks! I worked in all suggestions!

2017-02-23 14:23 UTC, rhatlapa commented
You need to also add snapshot repository to be able to use the creaper snapshot version
```
        <repository>
            <id>jboss-snapshots-repository</id>
            <name>JBoss Snapshots Repository</name>
            <url>https://repository.jboss.org/nexus/content/repositories/snapshots/</url>
        </repository>
```

2017-02-23 14:28 UTC, honza-kasik commented
Strange it did work for me locally...

2017-02-23 14:37 UTC, rhatlapa approved these changes

2017-02-23 14:39 UTC, rhatlapa commented
Please do reasonable squashing => it doesn't mean to single commit, it means to **several commits** with suitable chunks of work done.

2017-02-23 15:06 UTC, honza-kasik commented
@rhatlapa Thanks! WDYT? Is it enough?

2017-02-23 16:27 UTC, rhatlapa commented
Thanks, merging.

2017-02-23 16:27 UTC, merged