Tests for Elytron (aggregate) provider loader configuration.
hal/testsuite pull request #274
Opened 2017-03-24 16:26 UTC by zebrik

2017-03-28 15:04 UTC, honza-kasik requested changes
Thanks! I reviewed and I have one small issue - is navigating for second time necessary in mentioned test cases?

2017-03-28 15:04 UTC, honza-kasik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/elytron/ElytronProviderTestCase.java
> +        page.navigateToApplication().selectResource(PROVIDER_LOADER_LABEL);
Navigation is performed twice here or am I missing something?

2017-03-28 15:04 UTC, honza-kasik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/elytron/ElytronProviderTestCase.java
> +            page.navigateToApplication().selectResource(PROVIDER_LOADER_LABEL).getResourceManager()
Should this method call be here (second navigation)?

2017-03-28 15:04 UTC, honza-kasik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/elytron/ElytronProviderTestCase.java
> +            page.navigateToApplication().selectResource(AGGREGATE_PROVIDERS_LABEL).getResourceManager()
Navigating again...

2017-03-28 15:04 UTC, honza-kasik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/elytron/ElytronProviderTestCase.java
> +            ops.add(providerLoaderAddress);
IMO it would be better to append `#assertSuccess()`

2017-03-28 15:04 UTC, honza-kasik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/elytron/ElytronProviderTestCase.java
> +                    .and(CLASS_NAMES, new ModelNodeListBuilder(new ModelNode(BC_CLASS_NAME)).build()));
`#assertSuccess()`?

2017-03-28 15:04 UTC, honza-kasik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/elytron/ElytronProviderTestCase.java
> +                    .selectByName(aggregateProvidersName);
Navigating again?

2017-03-31 13:23 UTC, zebrik commented
@honza-kasik thank you for spotting the copy-paste navi issue. Can you review again?

2017-04-03 07:49 UTC, honza-kasik commented
@zebrik Thank you! Please squash commits and I will merge this.

2017-04-03 07:50 UTC, honza-kasik approved these changes

2017-04-03 08:10 UTC, zebrik commented
@honza-kasik squashed.

2017-04-03 08:12 UTC, merged

2017-04-03 08:12 UTC, honza-kasik commented
Merged! Thanks!