Fixed tests for transactions store
hal/testsuite pull request #310
Opened 2017-06-08 14:01 UTC by honza-kasik

2017-06-08 15:11 UTC, zebrik requested changes
Is it possible to add tests for testing functionality of `Use journal store` and `Use jdbc store` checkboxes as well? I understand it requires additional restarts - necessary cleanup may be done inside these new test methods. 
These new tests may be added in new PR if you prefer it.

2017-06-08 15:11 UTC, zebrik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/transactions/JDBCStoreTestCase.java
> +        client.apply(new RemoveDataSource(JDBC_STORE_DATASOURCE_NAME));
Removing datasource before restoring snapshot is not necessary IMO.

2017-06-08 15:11 UTC, zebrik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/transactions/JDBCStoreTestCase.java
> +            client.apply(new RemoveDataSource(datasource));
I don't suggest removing datasource which is still used in configuration.

2017-06-09 07:38 UTC, honza-kasik commented
Thanks! I added suggested tests (no restart needed after all) and fixed other suggestions too.

2017-06-09 08:00 UTC, zebrik commented
Thank you! Merging...

2017-06-09 08:00 UTC, merged