added tests for endpoint configuration in remoting subsystem
hal/testsuite pull request #331
Opened 2017-07-11 13:15 UTC by spriadka

2017-07-11 13:49 UTC, honza-kasik requested changes
I reviewed your code - which is just my point of view. In general, you created a good test coverage! Although, there are some files in which there are no changes, please remove those files from commit, in several files you also replace independent imports by `*`. This is against code style. For checking your code style, you can run:

```
mvn verify -Pbasic,rbac,transactions -fae -DskipTests=true -Dmaven.javadoc.skip=true -Djboss.dist -B
```

Just a note about abstract tests: This is IMHO not very handy when comes to rewriting/upgrading tests. I experienced it several times :)...

I see, that CI check is failing for unrelated reason, me or someone else will look into it ASAP.

2017-07-11 13:49 UTC, honza-kasik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/remoting/endpointconfiguration/EndpointConfigurationTestCaseAbstract.java
> +    protected void enterTextAndVerify(String inputField, String value) throws Exception {
Just a note: I started writing tests like these, but later it came out better for me to create as independent tests as possible... IMHO abstract methods like these make adapting new APIs and procedures more complicated.

2017-07-11 13:49 UTC, honza-kasik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/remoting/endpointconfiguration/EndpointConfigurationSecurityTestCase.java
> +    @InSequence
Tests have to be independent. Please, do not use `@InSequence`.

2017-07-11 13:49 UTC, honza-kasik commented on rbac/src/test/java/org/jboss/hal/testsuite/test/rbac/GroupScopedRoleTestCase.java
> +
Nothing really changed here, please remove this file from commit.

2017-07-11 13:49 UTC, honza-kasik commented on rbac/src/test/java/org/jboss/hal/testsuite/test/rbac/HostScopedRoleTestCase.java
> +
Nothing really changed here, please remove this file from commit.

2017-07-11 13:49 UTC, honza-kasik commented on rbac/src/test/java/org/jboss/hal/testsuite/test/rbac/ProfileAvailabilityTestCase.java
>  import org.openqa.selenium.WebDriver;
Nothing really changed here, please remove this file from commit.

2017-07-11 13:49 UTC, honza-kasik commented on rbac/src/test/java/org/jboss/hal/testsuite/test/rbac/RBACDomainAdminOperations.java
>  import java.io.IOException;
Nothing really changed here, please remove this file from commit.

2017-07-11 13:49 UTC, honza-kasik commented on rbac/src/test/java/org/jboss/hal/testsuite/test/rbac/RBACDomainOperations.java
> -
Nothing really changed here, please remove this file from commit.

2017-07-11 13:49 UTC, honza-kasik commented on rbac/src/test/java/org/jboss/hal/testsuite/test/rbac/RuntimeAccessErrorTestCase.java
>  import org.openqa.selenium.WebDriver;
Nothing really changed here, please remove this file from commit.

2017-07-11 13:49 UTC, honza-kasik commented on rbac/src/test/java/org/jboss/hal/testsuite/test/rbac/ServerAvailabilityTestCase.java
>  import java.util.NoSuchElementException;
Nothing really changed here, please remove this file from commit.

2017-07-11 13:49 UTC, honza-kasik commented on rbac/src/test/java/org/jboss/hal/testsuite/test/rbac/ServerGroupTestCase.java
Nothing really changed here, please remove this file from commit.

2017-07-11 13:49 UTC, honza-kasik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/remoting/endpointconfiguration/EndpointConfigurationTestCaseAbstract.java
> +        operations = new Operations(client);
Just a note: IMHO you can initialize these variables right away, there is no need for `@BeforeClass` in this case.

2017-07-11 13:49 UTC, honza-kasik commented on rbac/src/test/java/org/jboss/hal/testsuite/test/rbac/DatasourcesTestCase.java
>  import org.junit.experimental.categories.Category;
Please do not use `*` for importing classes. This is against code style.

2017-07-11 13:49 UTC, honza-kasik commented on rbac/src/test/java/org/jboss/hal/testsuite/test/rbac/DomainElementaryAccessControlTestCase.java
>  import org.jboss.hal.testsuite.finder.FinderNames;
Please do not use `*` for importing classes. This is against code style.

2017-07-11 13:49 UTC, honza-kasik commented on rbac/src/test/java/org/jboss/hal/testsuite/test/rbac/DomainElementaryAccessControlTestCase.java
>  import org.junit.experimental.categories.Category;
Please do not use `*` for importing classes. This is against code style.

2017-07-11 13:49 UTC, honza-kasik commented on rbac/src/test/java/org/jboss/hal/testsuite/test/rbac/DomainElementaryAccessControlTestCase.java
Please do not use `*` for importing classes. This is against code style.

2017-07-11 13:49 UTC, honza-kasik commented on rbac/src/test/java/org/jboss/hal/testsuite/test/rbac/ElementaryAccessControlTestCase.java
>  import org.jboss.hal.testsuite.finder.FinderNames;
Please do not use `*` for importing classes. This is against code style.

2017-07-11 13:49 UTC, honza-kasik commented on rbac/src/test/java/org/jboss/hal/testsuite/test/rbac/ElementaryAccessControlTestCase.java
>  import org.junit.experimental.categories.Category;
Please do not use `*` for importing classes. This is against code style.

2017-07-11 13:49 UTC, honza-kasik commented on rbac/src/test/java/org/jboss/hal/testsuite/test/rbac/ElementaryAccessControlTestCase.java
>  import org.wildfly.extras.creaper.core.online.OnlineManagementClient;
Please do not use `*` for importing classes. This is against code style.

2017-07-11 13:49 UTC, honza-kasik commented on rbac/src/test/java/org/jboss/hal/testsuite/test/rbac/RunAsTestCase.java
> +import static org.jboss.hal.testsuite.util.RbacRole.*;
Please do not use `*` for importing classes. This is against code style.

2017-07-12 14:27 UTC, honza-kasik commented
I fixed the CI check issue, it is already in master, just rebase and push ;)

2017-07-13 05:58 UTC, honza-kasik approved these changes

2017-07-13 05:58 UTC, honza-kasik commented
LGTM, just squash those two commits please, rebase, and if CI check goes well, I will merge this PR...

2017-07-14 08:26 UTC, honza-kasik commented
I see, that there is only one commit now, but its message its rather confusing. Please edit it to reflect changes made. It also looks like you haven't rebased yet, please do so, so the CI check can goe through...

2017-07-20 09:47 UTC, rhatlapa commented
Not properly rebased, your commits should appear as the newest ones.

2017-07-20 10:42 UTC, honza-kasik approved these changes
Looks good to me, although there are some minor issues, see comments for yourself. You don't have to implement suggestions, it is just for future reference.

When you are done, squash those three commits using `git rebase -i HEAD~3`, push changes and let me know.

2017-07-20 10:42 UTC, honza-kasik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/remoting/endpointconfiguration/EndpointConfigurationChannelsTestCase.java
> +        config.cancel();
We usually use `ConfigChecker.Builder.verifyFormNotSaved()` for these scenarios, but this is OK.

2017-07-20 10:42 UTC, honza-kasik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/remoting/endpointconfiguration/EndpointConfigurationAttributesTestCase.java
> +            Assert.assertNotNull(alert);
For the next time it would be IMHO better to extend `ConfigChecker.Builder`. But this is OK, since you are new to this...

2017-07-20 10:42 UTC, honza-kasik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/remoting/endpointconfiguration/EndpointConfigurationTestCaseAbstract.java
> +        new ResourceVerifier(ENDPOINT_CONFIGURATION_ADDRESS, client).verifyAttribute(inputField, value);
Why there is no `ConfigChecker` used anymore?

2017-07-20 10:42 UTC, honza-kasik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/remoting/endpointconfiguration/EndpointConfigurationAttributesTestCase.java
> +        config.cancel();
For this kind of scenarios we usually use `ConfigChecker.Builder#verifyFormNotSaved()`. But this is OK.

2017-07-20 12:51 UTC, merged