Ssl test case refactoring
hal/testsuite pull request #361
Opened 2017-11-09 10:56 UTC by spriadka

2017-11-13 11:23 UTC, zebrik requested changes

2017-11-13 11:23 UTC, zebrik commented on common/src/main/java/org/jboss/hal/testsuite/util/ModelNodeSerializable.java
> +public interface ModelNodeSerializable {
Please add JavaDoc.

2017-11-13 11:23 UTC, zebrik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/elytron/other/ssl/NewItem.java
> +
Please add JavaDoc.

2017-11-13 11:23 UTC, zebrik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/elytron/other/ssl/NewItemAttribute.java
> +public final class NewItemAttribute implements ModelNodeSerializable {
Please add JavaDoc.

2017-11-13 11:23 UTC, zebrik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/elytron/other/ssl/NewItem.java
> +
BTW why is this class named `NewItem` instead of `NewItemTemplate`?

2017-11-13 11:59 UTC, spriadka commented
@zebrik Thanks for the feedback. You were right, NewItemTemplate is more suitable than NewItem, anyway added javadoc and changed NewItem -> NewItemTemplate

2017-11-27 10:14 UTC, zebrik approved these changes

2017-11-27 10:14 UTC, zebrik commented
LGTM. Please squash a bit before the merge.

2017-11-29 08:21 UTC, merged