[JBEAP-14073] Add test coverage
hal/testsuite pull request #370
Opened 2018-03-28 12:05 UTC by mackaypeter

Adding test coverage for JBEAP-14073 / HAL-1389.

2018-03-29 09:15 UTC, mackaypeter commented
@zebrik Hi, could you please take a look? Thanks!

2018-04-19 12:01 UTC, zebrik requested changes
Just one formal requirement.

2018-04-19 12:01 UTC, zebrik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/datasources/DataSourcesConnectionTestCase.java
> +     * https://issues.jboss.org/browse/JBEAP-14073
This is upstream testsuite, co please reference related upstream HAL jira instead of the JBEAP one.

2018-04-19 12:01 UTC, zebrik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/datasources/DataSourcesConnectionTestCase.java
> +        Assert.assertEquals("Incorrect value of " + attribute  + " displayed. See https://issues.jboss.org/browse/JBEAP-14073", expectedValue, actualValue);
Please reference upstream jira.

2018-04-19 13:17 UTC, mackaypeter commented
@zebrik done, thanks for the review!

2018-04-19 14:09 UTC, merged

2018-04-19 14:10 UTC, zebrik commented
LGTM, thank you!