[Hal 1457] - Console 'Failed to create security context' if there are no data-sources
hal/testsuite pull request #371
Opened 2018-05-18 11:23 UTC by adamecp

JIRA upstream :  [https://issues.jboss.org/browse/HAL-1457](https://issues.jboss.org/browse/HAL-1457)

Description: In domain mode, if you add a xa-data-source and remove all of the data-sources, and reload server-one as requested. Then in the web console - Runtime / Server Group / main-server-group / server-one / Subsystems / Datasources / View gives error "Failed to create security context"

2018-05-18 13:05 UTC, zebrik requested changes
Just one minor objection related to cleaning up otherwise LGTM.

2018-05-18 13:05 UTC, zebrik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/datasources/CreateSecurityContextTestCase.java
> +        administration.reloadIfRequired();
Please close `client` at the end.

2018-05-21 05:20 UTC, adamecp reviewed
I have done it.

2018-05-21 08:47 UTC, zebrik approved these changes
Seems OK now. Thank you!

2018-05-21 08:50 UTC, merged