[HAL-1382] - Cannot set -1 value for connection-ttl via management console
hal/testsuite pull request #373
Opened 2018-06-05 10:30 UTC by adamecp

JIRA [https://issues.jboss.org/browse/HAL-1382](https://issues.jboss.org/browse/HAL-1382)

Description:  

Management console gives error "Invalid numeric value" when try to set connection-ttl value as -1
Configuration -> Subsystems -> Messaging - ActiveMQ -> Messaging Provider -> default -> Queue/Topics -> Connection Factories -> InVmConnectionFactory -> Connection Management -> Connection TTL

Via CLI it is possible to set it

    [standalone@localhost:9090 /] /subsystem=messaging-activemq/server=default/connection-factory=InVmConnectionFactory:write-attribute(name=connection-ttl,value=-1)
    Unknown macro: {"outcome" => "success"}

2018-06-05 11:03 UTC, zebrik requested changes

2018-06-05 11:03 UTC, zebrik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/messaging/connections/EditConnectionTestCase.java
> +        client.close();
I suggest to clean up the `client` in the same class where it is created - in the parent `AbstractMessagingTestCase`.

2018-06-05 11:03 UTC, zebrik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/messaging/connections/EditConnectionTestCase.java
> +        client = ManagementClientProvider.createOnlineManagementClient();
This is not necessary, the `client` is already created in the parent

2018-06-05 11:03 UTC, zebrik commented on basic/src/test/java/org/jboss/hal/testsuite/test/configuration/messaging/connections/EditConnectionTestCase.java
> +        page.edit().text("connectionTTL", "-1");
I would suggest using `AbstractMessagingTestCase#editTextAndVerify` for test logic implementation at least for the model change verification.

2018-06-06 09:18 UTC, adamecp commented
@zebrik Thanks for your review. I rewrite it according your comment.

2018-06-06 09:21 UTC, zebrik approved these changes

2018-06-06 09:22 UTC, zebrik commented
LGTM now. Thank you! Do you want me to merge it now?

2018-06-06 09:24 UTC, merged