[HAL-1511] - Cross-site scripting (XSS) in JBoss Management Console
hal/testsuite pull request #380
Opened 2018-11-08 13:21 UTC by adamecp

Jira task [https://issues.jboss.org/browse/HAL-1511](https://issues.jboss.org/browse/HAL-1511)
Description: There is a vulnerability in HAL not properly escaping html characters from resource names

PR to branch master [https://github.com/hal/testsuite/pull/379](https://github.com/hal/testsuite/pull/379)

2018-11-13 08:51 UTC, spriadka commented on basic/src/test/java/org/jboss/hal/testsuite/test/runtime/deployments/XssScriptingTestCase.java
> +        administration.reloadIfRequired();
Is the `administration.reloadIfRequired()` necessary before deployment?. If not I suggest calling this method after the deployment.

2018-11-13 08:54 UTC, spriadka commented on basic/src/test/java/org/jboss/hal/testsuite/test/runtime/deployments/XssScriptingTestCase.java
> +            administration.reloadIfRequired();
Are both `reload` and `restart` needed after the undeploy? If not, I suggest to `reload` only.

2018-11-13 08:59 UTC, spriadka commented on basic/src/test/java/org/jboss/hal/testsuite/test/runtime/deployments/XssScriptingTestCase.java
> +        client.apply(new DeployCommand.Builder(FILE_PATH + FILE_NAME)
I suggest replacing the `FILE_PATH + FILE_NAME` with `getClass().getResource()` syntax, as files present in the `src/test/resources` are available through this methods

2018-11-13 09:02 UTC, spriadka requested changes
Suggested some minor changes before merging, otherwise LGTM, thanks for the contribution @adamecp

2018-11-13 09:02 UTC, spriadka commented on basic/src/test/java/org/jboss/hal/testsuite/test/runtime/deployments/XssScriptingTestCase.java
> +    public static void setUp() throws IOException, TimeoutException, InterruptedException, CommandFailedException {
I suggest moving static methods & fields before instance methods & fields

2018-11-13 09:03 UTC, spriadka commented
Once this PR is resolved, feel free to merge #379 as well.

2018-11-16 10:25 UTC, adamecp reviewed
I rewrote it

2018-11-16 12:20 UTC, spriadka commented
Thanks @adamecp :+1: , just squash a bit and I'll merge it.

2018-11-16 12:20 UTC, spriadka approved these changes

2018-11-16 13:39 UTC, merged